version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf

  postgres:
    build: ./data/
    container_name: postgre-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: predictia
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data  # Volume nommé pour la persistance des données

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./docker-volumes/pgadmin-data:/var/lib/pgadmin  # Volume nommé pour la persistance des données de pgAdmin

volumes:
  postgres-data:  # Définition du volume nommé pour PostgreSQL
  pgadmin-data:   # Définition du volume nommé pour pgAdmin
